### ISSUE TITLE
api.query.staking.stakers is not a function error

### ISSUE THREAD

**Issue by ArseniiPetrovich** [ansonla3/kusama-validator-stats#5]
Hey, tried this script - not worked with the following error:
```
ubuntu@selfportal:~/kusama-validator-stats$ node index.js
(node:10858) UnhandledPromiseRejectionWarning: TypeError: api.query.staking.stakers is not a function
    at /home/ubuntu/kusama-validator-stats/index.js:88:54
```
Am I doing smth wrong?

OS: Ubuntu 18
Node: 12
Yarn: 1.22

**Comment by Swader** [comment]
No, you're fine, it's an API change. We'll have this fixed today. Thanks for reporting!

**Comment by ArseniiPetrovich** [comment]
Oh, great, thanks. Waiting for the fix! :)

**Comment by ansonla3** [comment]
@ArseniiPetrovich you may try again :)
